### ISSUE TITLE
Error on loading image

### ISSUE THREAD

**Issue by gehoida** [georgslazdans/outline-app#7]
Hi, when I try to process the attached image, I get the following error:

Failed to execute step: grayScaleObject, Exception: OpenCV(4.9.0) /build/4_x-contrib_docs-lin64/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::(anonymous namespace)::CvtHelper<cv::impl::(anonymous namespace)::Set<3, 4, -1>, cv::impl::(anonymous namespace)::Set<1, -1, -1>, cv::impl::(anonymous namespace)::Set<0, 2, 5>, cv::impl::(anonymous namespace)::NONE>::CvtHelper(cv::InputArray, cv::OutputArray, int) [VScn = cv::impl::(anonymous namespace)::Set<3, 4, -1>, VDcn = cv::impl::(anonymous namespace)::Set<1, -1, -1>, VDepth = cv::impl::(anonymous namespace)::Set<0, 2, 5>, sizePolicy = cv::impl::(anonymous namespace)::NONE]' > Invalid number of channels in input image: > 'VScn::contains(scn)' > where > 'scn' is 1
Background Image
Settings
![Untitled](https://github.com/user-attachments/assets/27501119-55f0-4d20-8dc5-07a0b9d970c2)

**Comment by georgslazdans** [comment]
Hi!
At the moment the error handling is almost non existent and the error message should be "Paper contours not found!". I am working on it to implement that.

As for the image, the background has similar values to paper in gray scale and causes paper outline to have holes in the threshold step. The easiest fix would be to have background that is of different color around the paper and provides good contrast. 
![Outlined_grayscale](https://github.com/user-attachments/assets/1b45f7b3-9da8-4ef3-b9df-2db1f838cc7d)
![small_threshold](https://github.com/user-attachments/assets/db998fb1-15ef-489e-a1b7-8a428fe54b9b)

To solve this with software would require a bit more knowledge of image processing than I currently have or to do some kind of line reconstruction for the contours it can find. Both of which would take a fairly long time to implement.

**Comment by georgslazdans** [comment]
Did some refactoring and added a visible error message when the paper outline is not found.
![Screenshot from 2024-09-15 13-06-45](https://github.com/user-attachments/assets/b0ecec7d-554c-4293-92ad-06f62fada574)
