### ISSUE TITLE
Feature Request: Customizable grid size

### ISSUE THREAD

**Issue by matt-sorenson** [georgslazdans/outline-app#8]
I do many models where the 42mm grid ends up being huge and wasting lots of space, for my models I set the bins to use half size grids, which ends up being 100% compatible with the default grid plates but wastes less space on the grid, less time & filament.

**Comment by georgslazdans** [comment]
I mostly "borrowed" the implementation from the [official docs](https://replicad.xyz/docs/examples/gridfinity), but as far as I can tell, that should be quite simple to change the grid size from a constant to an editable parameter. Will give it a go after I done fixing error handling in the calibration part.

**Comment by georgslazdans** [comment]
Added a new parameter "Grid Size" to the Gridfinity parameters and the changes are available online!

Did a small test print and seemed to mesh fine with the regular grid. If there are any problems, feel free to open another issue.
