### ISSUE TITLE
Add descriptive error messages

### ISSUE THREAD

**Issue by kilpatrq** [georgslazdans/outline-app#9]
I've been trying to upload an image on mobile for some time, and after entering a name and selecting an orientation and paper size, I hit "find outline" and i get an animation of a spinning circle for half a second and then get kicked right back to the form. I don't really have any information i can open an issue with, so i think a descriptive error message would be helpful.

**Comment by georgslazdans** [comment]
Sounds like there is an error while saving to IndexedDB. Maybe some kind of storage issue.

There are a few places where errors are just logged to console. I will create a error popup that should give copyable error info on mobile.

**Comment by georgslazdans** [comment]
I added a error modal and it will pop up when an error occurs.
